apiVersion: v1
kind: Service
metadata:
  name: curbsider
  namespace: curbsider
  labels:
    app: curbsider
spec:
  selector:
    app: curbsider
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
